### ISSUE TITLE
Parse Error when using REST client behind proxy

### ISSUE THREAD

**Issue by super132** [aacerox/node-rest-client#16]
Hi,

I have experienced an error throwing from Socket.socketOnData method when calling REST client behind a proxy. Here is the code I used:

``` javascript
var RestClient = require('node-rest-client').Client, 
    client = new RestClient({
        proxy:{
            host:"proxyDomain",
            port: 8080,
            user:"username",
            password:"password"
        }
    });

client.registerMethod("jsonMethod", "http://ogcef.one.gov.hk/event-psi/json/calendar/20140215.json", "GET");

client.methods.jsonMethod(function (data, response) {...});
```

After checking up the REST client code a bit, I found that it will try to connect to proxy via 'CONNECT' method using Node.js http client and then making another connection after this call returned successfully. The issue is that if you use Node.js http client to trigger a call using 'CONNECT' method, the above exception is thrown. 

May I suggest to use something similiar below so that REST client can connect to the target URL successfully behind a proxy environment? I have tested in my local and it works:

``` javascript
var request = http.request({
    host: 'proxy',
    port: '8080',
    method: 'GET',
    path: 'http://ogcef.one.gov.hk/event-psi/json/calendar/20140215.json',
    headers: {
        'host': 'ogcef.one.gov.hk',
        'Proxy-Authentication': 'Basic ' + new Buffer(['username','password'].join(":")).toString("base64")
    },
    agent: false
}); 
```

Is it possible to change ConnectManager.proxy function to use the approach above instead of making a CONNECT call?

Thanks and this package is an awesome package for Node.js :)

Sincerely,
Jason

**Comment by HarshaJagadish** [comment]
Hello @aacerox ,
I know its been a long time since this issue was fixes but I am still facing issue. The client is unable to complete the request when inside a proxy. The SSL hand shake fails to connect to the server. below is my set up for the proxy
`options_proxy = {
      proxy: {
          host: "192.168.2.55",
          port: 8888,
          tunnel: true
      }
  };
  globalproxySet = true;
  client = new Client(options_proxy);`

I have the client response as follows after the set up 

`EventEmitter {
  options: { proxy: { host: '<my local IP>', port: 8888, tunnel: true } },
  useProxy: true,
  useProxyTunnel: true,
  proxy: { host: '<My IP>', port: 8888, tunnel: true },
  connection: {},
  mimetypes: {},
  requestConfig: {},
  responseConfig: {},
  methods: {},
  parsers: 
   { add: [Function],
     remove: [Function],
     find: [Function],
     getAll: [Function],
     getDefault: [Function],
     clean: [Function] },
  serializers: 
   { add: [Function],
     remove: [Function],
     find: [Function],
     getAll: [Function],
     getDefault: [Function],
     clean: [Function] },
  get: [Function],
  post: [Function],
  put: [Function],
  delete: [Function],
  patch: [Function],
  registerMethod: [Function],
  unregisterMethod: [Function],
  addCustomHttpMethod: [Function] }`

I am using Charles for proxy settings. Please let me know what am I doing wrong.
