### ISSUE TITLE
Non-tunneled proxy requests not always working

### ISSUE THREAD

**Issue by mjwwit** [aacerox/node-rest-client#76]
Non-tunneled proxy requests do not always lead to a successful response.

I have narrowed the issue down to the absence of a `host` header in the request.
It appears there is support for the `host` header, and it is initially filled correctly. Later on it gets deleted from the options though, leaving the request without the header entirely.

**Comment by aacerox** [comment]
Hi
First of all thanks for your advice on this bug, but I can't apply your pull request because it doesn't fix completely the bug created in the last version with POST/PUT/DELETE/PATCH method headers (I've had to append those headers mentioned before to non-tunnel proxy headers not just delete options.headers = {} assignment).

Current version (1.5.1) fix this issue.

Thanks again.
